---
title: "Final Project"
author: "Lucas Fox, Nathalie Kirsch, Vanaaisha Pamnani, and Cuong Pham Vu"
date: "4/18/2022"
output: html_document
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r include = FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

### PPOL 670 | Final Project

This assignment is stored on the following [Github repository](https://github.com/nakirsch/PPOL670_FinalProject). 

```{r}
library(tidyverse)
library(tidycensus)
library(tidymodels)
library(ggplot2)
library(patchwork)
library(httr)
library(jsonlite)
library(sf)
library(janitor)
library(lubridate)
library(stringr)
library(factoextra)


theme_set(theme_minimal())
```



```{r}


crime_data22 <- st_read("Crime_Incidents_in_2022.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

crime_data21 <- st_read("Crime_Incidents_in_2021.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

crime_data20 <- st_read("Crime_Incidents_in_2020.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

crime_data19 <- st_read("Crime_Incidents_in_2019.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()


policestations <- st_read("Police_Stations.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()


crime_data_total <- rbind(crime_data22, crime_data21)
crime_data_total <- rbind(crime_data_total, crime_data20)
crime_data_total <- rbind(crime_data_total, crime_data19)

crime_data_total_2 <- crime_data_total %>%
  separate(
    col = report_dat,
    into = c("date", "time"),
    sep = " ",
    remove = TRUE
  ) %>%
  mutate(year = year(date),
         month = month(date))

dctracts <- st_read("Census_Tracts_in_2010.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

#crime_merged_agg <- crime_data_total_2 %>%
#  group_by(census_tract) %>%
#  summarize(count = n()) %>%
#  rename(tract = census_tract)

#class(crime_merged_agg)

#Visualizations

crime_merged <- st_join(dctracts, crime_data_total_2, join = st_contains, left = TRUE) 

crime_merged_agg <- crime_merged %>%
  group_by(tract, year) %>%
  summarize(count = n(),
            population = mean(p0030001),
            year = mean(year)) %>%
  mutate(crimerate = count/population*1000)

pop_map <- ggplot() +
   geom_sf(
    data = dctracts,
    aes(fill = p0010001)
) +
  scale_fill_gradient(low = "blue",
                      high = "red") +
  labs(title = "Tract population in 2019") +
  theme_void()

crimerate_map <- ggplot() +
   geom_sf(
    data = crime_merged_agg %>% filter(tract != "006202"),
    aes(fill = crimerate),
    color = "white"
) +
  scale_fill_gradient2() +
  facet_wrap(~year) +
  labs(title = "Crime rate in census tracts by year") +
  theme_void()

crime_police21 <- ggplot() +
  geom_sf(
    data = dctracts,
    fill = "white"
) +
  geom_sf(
    data = crime_data_total_2 %>% filter(year == 2021),
    color = "light pink",
    alpha = 0.05
) +
  geom_sf(
    data = policestations,
    color = "blue"
  ) +
  theme_void()

pop_map

crimerate_map

crime_police21

```


``` {r}

# tidycensus for 2019 ACS data

varlist <- load_variables(2019, "acs5/profile", cache = TRUE)
  
vars <- as.character(varlist$name)
  
acs_2019 <- get_acs(geography = "tract",
               state = 11,
               variables = vars,
               year = 2019,
               output = "wide")

acs_2019 <- acs_2019 %>%
  mutate(tract = str_sub(GEOID, 6, 11))

crime_acs_merged <- left_join(crime_merged_agg %>% st_drop_geometry() %>% filter(year == 2019), 
                              acs_2019, 
                              by = "tract")

# PCA ANALYSIS (NOT SURE ABOUT THIS)

crime_acs_numeric <- crime_acs_merged %>% 
  select_if(is.numeric) %>%
  select(-contains(c("PM","M","PE"))) %>%
  ungroup() %>%
  select(-tract)


crime_acs_numeric <- crime_acs_numeric %>%
  select_if(~ !any(is.na(.)))

crime_pca <- prcomp(crime_acs_numeric)

crime_pca$rotation

# CLUSTER ANALYSIS (NOT SURE ABOUT THIS)

# create a recipe with no outcome variable and all predictors
clust_rec <- recipe(~., data = crime_acs_numeric %>% mutate(crimerate = count/population*1000) %>% select(-year)) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors()) %>%
  prep()

crime_clust <- clust_rec %>%
  bake(new_data = NULL)

principal_components <- prcomp(~ ., data=crime_clust, na.action=na.omit)

summary(principal_components)

pca_data <- as_tibble(principal_components$x) %>%
  select(PC1, PC2, PC3)


# set a seed because the clusters are not deterministic
set.seed(20200205)

# total within sum of squares
fviz_nbclust(crime_clust, FUN = kmeans, method = "wss")

# total silhouette width
fviz_nbclust(crime_clust, FUN = kmeans, method = "silhouette")

# gap statistic
fviz_nbclust(crime_clust, FUN = kmeans, method = "gap_stat")




# LASSO MODEL PREDICTING CRIME COUNT

set.seed(20220503)

crime_split <- initial_split(data = crime_acs_numeric  %>% select(-year), prop = 0.8)

crime_train <- training(x = crime_split)

crime_test <- testing(x = crime_split)

crime_rec <- recipe(count ~ ., data = crime_train) %>%
  step_scale(all_predictors()) %>%
  step_center(all_predictors())

folds <- vfold_cv(data = crime_train, v = 10, repeats = 3)

lasso_grid <- grid_regular(penalty(), levels = 10)

lasso_mod <- linear_reg(
  penalty = tune(),
  mixture = 1) %>%
  set_engine("glmnet", path_values = lasso_grid$penalty)

lasso_wf <- workflow() %>%
  add_recipe(crime_rec)%>%
  add_model(lasso_mod)

#lasso_cv <- lasso_wf %>%
#  tune_grid(resample = folds, 
#            grid = lasso_grid)

get_glmnet_coefs <- function(x) {
  
  x %>% 
    extract_fit_engine() %>% 
    tidy(return_zeros = TRUE) %>% 
    rename(penalty = lambda)
  
}

parsnip_ctrl <- control_grid(extract = get_glmnet_coefs)

# estimate the models using tune_grid, setting the control argument to parsnip_ctrl
# and any other arguments that are needed by modifying the line below
lasso_cv <- lasso_wf %>%
  tune_grid(
    resamples = folds,
    grid = lasso_grid,
    control = parsnip_ctrl
  )

bind_rows(
  LASSO = show_best(lasso_cv, n = 1),
  .id = "model"
)

lasso_coefs <- 
  lasso_cv %>% 
  select(id, .extracts) %>% 
  unnest(.extracts) %>% 
  select(id, .extracts) %>% 
  unnest(.extracts) %>%
  group_by(id, term, penalty) %>%
  slice(1) %>%
  ungroup()


lasso_best <- lasso_cv %>% select_best("rmse")

lasso_final <- finalize_workflow(
  lasso_wf,
  parameters = lasso_best
)

lasso_fit <- lasso_final %>%
  fit(data = crime_test)

predictions <- bind_cols(
    crime_test,
    predict(object = lasso_fit, new_data = crime_test)
)

rmse(data = predictions, truth = count, estimate = .pred)


```