---
title: "Final Project"
author: "Lucas Fox, Nathalie Kirsch, Vanaaisha Pamnani, and Cuong Pham Vu"
date: "4/18/2022"
output: html_document
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r include = FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

### PPOL 670 | Final Project

This assignment is stored on the following [Github repository](https://github.com/nakirsch/PPOL670_FinalProject). 

```{r}
library(tidyverse)
library(tidycensus)
library(tidymodels)
library(ggplot2)
library(patchwork)
library(httr)
library(jsonlite)
library(sf)
library(janitor)
library(lubridate)
library(stringr)
library(factoextra)


theme_set(theme_minimal())
```


```{r}
# Reading in crime data

crime_data22 <- st_read("data/Crime_Incidents_in_2022.geojson") %>%
  clean_names()
crime_data21 <- st_read("data/Crime_Incidents_in_2021.geojson") %>%
  clean_names()
crime_data20 <- st_read("data/Crime_Incidents_in_2020.geojson") %>%
  clean_names()
crime_data19 <- st_read("data/Crime_Incidents_in_2019.geojson") %>%
  clean_names()
crime_data18 <- st_read("data/Crime_Incidents_in_2018.geojson") %>%
  clean_names()
crime_data17 <- st_read("data/Crime_Incidents_in_2017.geojson") %>%
  clean_names()
crime_data16 <- st_read("data/Crime_Incidents_in_2016.geojson") %>%
  clean_names()
crime_data15 <- st_read("data/Crime_Incidents_in_2015.geojson") %>%
  clean_names()
crime_data14 <- st_read("data/Crime_Incidents_in_2014.geojson") %>%
  clean_names()
crime_data13 <- st_read("data/Crime_Incidents_in_2013.geojson") %>%
  clean_names()
crime_data12 <- st_read("data/Crime_Incidents_in_2012.geojson") %>%
  clean_names()
crime_data11 <- st_read("data/Crime_Incidents_in_2011.geojson") %>%
  clean_names()
crime_data10 <- st_read("data/Crime_Incidents_in_2010.geojson") %>%
  clean_names()

crime_data_2010s <- rbind(crime_data20, crime_data19)
crime_data_2010s <- rbind(crime_data_2010s, crime_data18)
crime_data_2010s <- rbind(crime_data_2010s, crime_data17)
crime_data_2010s <- rbind(crime_data_2010s, crime_data16)
crime_data_2010s <- rbind(crime_data_2010s, crime_data15)
crime_data_2010s <- rbind(crime_data_2010s, crime_data14)
crime_data_2010s <- rbind(crime_data_2010s, crime_data13)
crime_data_2010s <- rbind(crime_data_2010s, crime_data12)
crime_data_2010s <- rbind(crime_data_2010s, crime_data11)
crime_data_2010s <- rbind(crime_data_2010s, crime_data10)


# Reading in police stations

policestations <- st_read("Police_Stations.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

crime_data_total <- crime_data_2010s %>%
  separate(
    col = report_dat,
    into = c("date", "time"),
    sep = " ",
    remove = TRUE
  ) %>%
  mutate(year = year(date),
         month = month(date))

dctracts <- st_read("Census_Tracts_in_2010.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

crime_merged <- st_join(dctracts, crime_data_total_2, join = st_contains, left = TRUE) 

crime_merged_agg <- crime_merged %>%
  group_by(tract, year) %>%
  summarize(count = n(),
            population = mean(p0030001),
            year = mean(year)) %>%
  mutate(crimerate = count/population*1000)

write.csv(crime_merged_agg, file ="crime_merged_agg.csv")


# tidycensus for 2019 ACS data

varlist20 <- load_variables(2020, "acs5/profile", cache = TRUE)
  
vars20 <- as.character(varlist20$name)
  
acs_2020 <- get_acs(geography = "tract",
               state = 11,
               variables = vars20,
               year = 2020,
               output = "wide")

acs_2020 <- acs_2020 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2020)


varlist19 <- load_variables(2019, "acs5/profile", cache = TRUE)
  
vars19 <- as.character(varlist19$name)
  
acs_2019 <- get_acs(geography = "tract",
               state = 11,
               variables = vars19,
               year = 2019,
               output = "wide")

acs_2019 <- acs_2019 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2019)

varlist18 <- load_variables(2018, "acs5/profile", cache = TRUE)
  
vars18 <- as.character(varlist18$name)

acs_2018 <- get_acs(geography = "tract",
               state = 11,
               variables = vars18,
               year = 2018,
               output = "wide")

acs_2018 <- acs_2018 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2018)

varlist17 <- load_variables(2017, "acs5/profile", cache = TRUE)
  
vars17 <- as.character(varlist17$name)

acs_2017 <- get_acs(geography = "tract",
               state = 11,
               variables = vars17,
               year = 2017,
               output = "wide")

acs_2017 <- acs_2017 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2017)

varlist16 <- load_variables(2016, "acs5/profile", cache = TRUE)
  
vars16 <- as.character(varlist16$name)

acs_2016 <- get_acs(geography = "tract",
               state = 11,
               variables = vars16,
               year = 2016,
               output = "wide")

acs_2016 <- acs_2016 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2016)

varlist15 <- load_variables(2015, "acs5/profile", cache = TRUE)
  
vars15 <- as.character(varlist15$name)

acs_2015 <- get_acs(geography = "tract",
               state = 11,
               variables = vars15,
               year = 2015,
               output = "wide")

acs_2015 <- acs_2015 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2015)


varlist14 <- load_variables(2014, "acs5/profile", cache = TRUE)
  
vars14 <- as.character(varlist14$name)

acs_2014 <- get_acs(geography = "tract",
               state = 11,
               variables = vars14,
               year = 2014,
               output = "wide")

acs_2014 <- acs_2014 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2014)

varlist13 <- load_variables(2013, "acs5/profile", cache = TRUE)
  
vars13 <- as.character(varlist13$name)

acs_2013 <- get_acs(geography = "tract",
               state = 11,
               variables = vars13,
               year = 2013,
               output = "wide")

acs_2013 <- acs_2013 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2013)

varlist12 <- load_variables(2012, "acs5/profile", cache = TRUE)
  
vars12 <- as.character(varlist12$name)

acs_2012 <- get_acs(geography = "tract",
               state = 11,
               variables = vars12,
               year = 2012,
               output = "wide")

acs_2012 <- acs_2012 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2012)

varlist11 <- load_variables(2011, "acs5/profile", cache = TRUE)
  
vars11 <- as.character(varlist11$name)

acs_2011 <- get_acs(geography = "tract",
               state = 11,
               variables = vars11,
               year = 2011,
               output = "wide")

acs_2011 <- acs_2011 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2011)

varlist10 <- load_variables(2010, "acs5/profile", cache = TRUE)
  
vars10 <- as.character(varlist10$name)

acs_2010 <- get_acs(geography = "tract",
               state = 11,
               variables = vars10,
               year = 2010,
               output = "wide")

acs_2010 <- acs_2010 %>%
  mutate(tract = str_sub(GEOID, 6, 11)) %>%
  mutate(year = 2010)

acs <- bind_rows(acs_2019, acs_2018)
acs <- bind_rows(acs, acs_2017)
acs <- bind_rows(acs, acs_2016)
acs <- bind_rows(acs, acs_2015)
acs <- bind_rows(acs, acs_2014)
acs <- bind_rows(acs, acs_2013)
acs <- bind_rows(acs, acs_2012)
acs <- bind_rows(acs, acs_2011)
acs <- bind_rows(acs, acs_2010)
acs <- bind_rows(acs, acs_2020)

write.csv(acs, file = "acs_merged")

```



```{r}

# VISUALIZATIONS AND GEOSPATIAL ANALYSIS

crime_merged_agg <- read_csv("data/crime_merged_agg.csv")

dctracts <- st_read("Census_Tracts_in_2010.geojson") %>%
  st_set_crs(value = 4326) %>%
  clean_names()

pop_map <- ggplot() +
   geom_sf(
    data = dctracts,
    aes(fill = p0010001)
) +
  scale_fill_gradient(low = "blue",
                      high = "red") +
  labs(title = "Tract population in 2019") +
  theme_void()

pop_map

crimerate_map <- ggplot() +
   geom_sf(
    data = crime_merged_agg %>% filter(tract != "006202"),
    aes(fill = crimerate),
    color = "white"
) +
  scale_fill_gradient2() +
  facet_wrap(~year) +
  labs(title = "Crime rate in census tracts by year") +
  theme_void()

crimerate_map

crime_police21 <- ggplot() +
  geom_sf(
    data = dctracts,
    fill = "white"
) +
  geom_sf(
    data = crime_data21,
    color = "light pink",
    alpha = 0.05
) +
  geom_sf(
    data = policestations,
    color = "blue"
  ) +
  theme_void()

crime_police21

```


``` {r}

crime_merged_agg <- read_csv("data/crime_merged_agg.csv")

acs_merged <- read_csv("data/acs_merged")

crime_acs_merged <- left_join(crime_merged_agg %>% st_drop_geometry() %>% filter(year < 2020), 
                              acs_merged %>% filter(year < 2020), 
                              by = c("tract","year"))

crime_acs_numeric <- crime_acs_merged %>% 
  select_if(is.numeric) %>%
  select(-contains(c("PM","M","PE"))) %>%
  ungroup() %>%
  select(-tract)

crime_acs_numeric <- crime_acs_numeric %>%
  select_if(~ !any(is.na(.)))


#PCA ANALYSIS (NOT SURE ABOUT THIS)

crime_pca <- prcomp(crime_acs_numeric %>% select(-year, -count))

summary(crime_pca)

crime_pca$rotation

```

```{r}

# LASSO MODEL PREDICTING CRIME COUNT WITH ALL PREDICTORS

set.seed(20220503)

crime_split <- initial_split(data = crime_acs_numeric %>% filter(year < 2019) %>% select(-year), prop = 0.8)

crime_train <- training(x = crime_split)

crime_test <- testing(x = crime_split)

crime_rec <- recipe(count ~ ., data = crime_train) %>%
  step_scale(all_predictors()) %>%
  step_center(all_predictors())

folds <- vfold_cv(data = crime_train, v = 10, repeats = 10)

lasso_grid <- grid_regular(penalty(), levels = 10)

lasso_mod <- linear_reg(
  penalty = tune(),
  mixture = 1) %>%
  set_engine("glmnet", path_values = lasso_grid$penalty)

lasso_wf <- workflow() %>%
  add_recipe(crime_rec)%>%
  add_model(lasso_mod)

get_glmnet_coefs <- function(x) {
  
  x %>% 
    extract_fit_engine() %>% 
    tidy(return_zeros = TRUE) %>% 
    rename(penalty = lambda)
  
}

parsnip_ctrl <- control_grid(extract = get_glmnet_coefs)

lasso_cv <- lasso_wf %>%
  tune_grid(
    resamples = folds,
    grid = lasso_grid,
    control = parsnip_ctrl
  )

bind_rows(
  LASSO = show_best(lasso_cv, n = 1),
  .id = "model"
)

lasso_coefs <- 
  lasso_cv %>% 
  select(id, .extracts) %>% 
  unnest(.extracts) %>% 
  select(id, .extracts) %>% 
  unnest(.extracts) %>%
  group_by(id, term, penalty) %>%
  slice(1) %>%
  ungroup()


lasso_best <- lasso_cv %>% select_best("rmse")

lasso_final <- finalize_workflow(
  lasso_wf,
  parameters = lasso_best
)

lasso_fit <- lasso_final %>%
  fit(data = crime_train)

predictions <- bind_cols(
    crime_test,
    predict(object = lasso_fit, new_data = crime_test)
)


rmse(data = predictions, truth = count, estimate = .pred)

predictions <- bind_cols(
    crime_acs_numeric,
    predict(object = lasso_fit, new_data = crime_acs_numeric)
)

rmse(data = predictions, truth = count, estimate = .pred)

predictions %>%
  group_by(year) %>% 
  mutate(.pred = if_else(.pred < 0, 0, .pred)) %>%
  summarize(actual = sum(count),
            predicted = sum(.pred))
 
view(predictions %>% select(count, .pred))

tidy(lasso_fit)


```

```{r}

# LASSO MDOEL PREDICTING CRIME COUNT WITH SELECTED PREDICTORS

crimes_acs_main  <- crime_acs_merged %>%
  select(DP02_0059PE, DP02_0060PE, DP02_0061PE, DP02_0062PE, DP02_0063PE, DP02_0064PE, DP02_0065PE, DP02_0066PE, DP02_0067PE, DP02_0068PE, DP05_0037PE, DP05_0038PE, DP05_0039PE, DP05_0044PE, DP05_0052PE, DP05_0058PE, DP03_0086E, DP02_0016E, DP02_0017E, DP02_0002PE, DP02_0010PE, year, count, population)

crimes_acs_2019 <- crime_acs_merged %>%
  filter(year == 2019) %>%
  select(DP02_0059PE, DP02_0060PE, DP02_0061PE, DP02_0062PE, DP02_0063PE, DP02_0064PE, DP02_0065PE, DP02_0066PE, DP02_0067PE, DP02_0068PE, DP05_0037PE, DP05_0038PE, DP05_0039PE, DP05_0044PE, DP05_0052PE, DP05_0058PE, DP03_0086E, DP02_0016E, DP02_0017E, DP02_0002PE, DP02_0010PE, year, count, population)

crimes_acs_2020 <- crime_acs_merged %>%
  filter(year == 2020) %>%
  select(DP02_0059PE, DP02_0060PE, DP02_0061PE, DP02_0062PE, DP02_0063PE, DP02_0064PE, DP02_0065PE, DP02_0066PE, DP02_0067PE, DP02_0068PE, DP05_0037PE, DP05_0038PE, DP05_0039PE, DP05_0044PE, DP05_0052PE, DP05_0058PE, DP03_0086E, DP02_0016E, DP02_0017E, DP02_0002PE, DP02_0010PE, year, count, population)


crimes_acs_main <- crimes_acs_main %>%
  select_if(is.numeric) %>%
  ungroup() %>%
  select(-"tract")
 
crimes_acs_2020 <- crimes_acs_2020 %>%
  select_if(is.numeric) %>%
  ungroup() %>%
  select(-"tract")

crimes_acs_2019 <- crimes_acs_2019 %>%
  select_if(is.numeric) %>%
  ungroup() %>%
  select(-"tract")


crimemain_split <- initial_split(data = crimes_acs_main %>% filter(year < 2019) %>% select(-year), prop = 0.8)

crimemain_train <- training(x = crimemain_split)

crimemain_test <- testing(x = crimemain_split)

crimemain_rec <- recipe(count ~ ., data = crimemain_train) %>%
  step_scale(all_predictors()) %>%
  step_center(all_predictors())

folds1 <- vfold_cv(data = crimemain_train, v = 10, repeats = 5)

lassomain_grid <- grid_regular(penalty(), levels = 10)

lassomain_mod <- linear_reg(
  penalty = tune(),
  mixture = 1) %>%
  set_engine("glmnet", path_values = lasso_grid$penalty)

lassomain_wf <- workflow() %>%
  add_recipe(crimemain_rec)%>%
  add_model(lassomain_mod)

lassomain_cv <- lassomain_wf %>%
  tune_grid(
    resamples = folds1,
    grid = lasso_grid,
    control = parsnip_ctrl
  )

bind_rows(
  LASSO = show_best(lassomain_cv, n = 1),
  .id = "model"
)

lassomain_coefs <-
  lassomain_cv %>%
  select(id, .extracts) %>%
  unnest(.extracts) %>%
  select(id, .extracts) %>%
  unnest(.extracts) %>%
  group_by(id, term, penalty) %>%
  slice(1) %>%
  ungroup()

lassomain_best <- lassomain_cv %>% select_best("rmse")

lassomain_final <- finalize_workflow(
  lassomain_wf,
  parameters = lassomain_best
)

lassomain_fit <- lassomain_final %>%
  fit(data = crimemain_train)

predictions_main <- bind_cols(
    crimemain_test,
    predict(object = lassomain_fit, new_data = crimemain_test)
)

rmse(data = predictions, truth = count, estimate = .pred)

predictions19_main <- bind_cols(
    crimes_acs_main,
    predict(object = lassomain_fit, new_data = crimes_acs_main)
)

rmse(data = predictions19_main, truth = count, estimate = .pred)

predictions19_main %>%
  group_by(year) %>%
  summarize(actual = sum(count),
            predicted = sum(.pred))

tidy(lassomain_fit) %>%
  filter(estimate != 0)
```